### ISSUE TITLE
No Credit Card Option Appearing at Checkout

### ISSUE THREAD

**Issue by danbolick** [solution25com/nmi-payment-shopware-6-solution25#3]
I've installed the NMI Payment Shopware 6 plugin and configured it correctly (or at least think so), but the credit card payment option doesn't appear during the checkout process. 

## Steps to Reproduce

Installed the plugin via Shopware plugin manager
Configured the plugin with valid private & public key values in the plugin config page
Enabled the customer for NMI payments
Verified NMI payment is available within the payment methods in the Admin portal
Proceeded to checkout as a customer
Expected to see credit card payment option but it's not visible

### Current Behavior

The payment method is configured correctly and visible in the Admin portal, but no credit card option appears during the actual checkout process.
### Expected Behavior
Credit card payment option should be visible and selectable during checkout.
Environment

Shopware version: 6.6.10.3 (Free install, no other plugins install excluding the demo products)
Plugin version: 1.0.4
Browser: Chrome

I've confirmed the plugin is activated
I can see the NMI payment method listed in the Admin payment methods section

Note: also, the customer profile shows the naming as `NMI Stored cards`, which would be confusing to the customer as they would have no context of what `NMI` means.

![Image](https://github.com/user-attachments/assets/c4f53ca7-2201-4bb6-b08e-c87a55eee4cb)

![Image](https://github.com/user-attachments/assets/51bc3f00-c4bc-4bb9-baef-73700760d4e6)

![Image](https://github.com/user-attachments/assets/910a0b0d-7324-426b-b6c0-2cf17a05bddf)

![Image](https://github.com/user-attachments/assets/51b141ad-5ec5-4e67-90d6-58ea6b0814d9)

![Image](https://github.com/user-attachments/assets/9ad10f14-6301-4d2f-84e3-0f11b58611f0)

**Comment by solution-25** [comment]
Hi @danbolick,

Thank you for reporting this and providing clear steps — that was very helpful! We've investigated the issue and made several updates and improvements to the plugin. Here's a summary of what we've addressed:

### Payment Method Visibility in Checkout
To ensure the NMI credit card options appear during checkout, please go to the  
**Sales Channel → Storefront → Payment Methods** section in the Admin panel.  
Make sure both **NMI Credit Card** and **NMI ACH** payment methods are assigned to the sales channel.  
You can also set your preferred method as the **default payment method** for a smoother customer experience.

![Image](https://github.com/user-attachments/assets/1ed26961-0690-4922-96e7-242d4276c8cb)

### Updated Payment Method Naming
We've updated the display name from **"NMI Saved Cards"** to simply **"Saved Cards"** to reduce confusion for customers and keep the naming user-friendly and intuitive.

![Image](https://github.com/user-attachments/assets/74d17d74-f57b-4504-ac21-6c1025475ad6)

### Improved Security: Masked API Keys
In the plugin configuration page, all sensitive fields (such as the API private keys) are now properly **masked using password fields** to prevent unintended visibility.

### Separated Sandbox and Live Configuration
We've separated the **Sandbox** and **Production** key inputs to avoid misconfiguration and make environment management more clear.

![Image](https://github.com/user-attachments/assets/1ce79394-2526-4dab-9b15-5b45bd2d3582)
![Image](https://github.com/user-attachments/assets/5f5c6e8d-6439-4836-96f3-337f366c7352)

---

These changes should resolve the issue and improve the user experience during checkout. If you're still encountering any problems, feel free to reach out and we’ll be happy to assist further.

Thanks again for your feedback and for using our NMI plugin!

Best regards,  
**Solution25**

**Comment by danbolick** [comment]
@solution-25  I am still having a problem. Will the changes around Sandbox / Production be in a future release?
So I'm still not seeing the credit card form on the Checkout page, nor the customer profile. 
As a confirmation, the "Api Private key" = NMI's Private Security Key with API Source &
"Api public key" = NMI Public Security Keys with Tokenization Source?

**Comment by solution-25** [comment]
Hi @danbolick ,

Thank you for your patience and for the additional details.

We would like to confirm that we are preparing a new release today, which includes important updates related to Sandbox/Production environment handling, as well as improvements for the visibility of the credit card form both during checkout and in the customer profile.

Regarding your question:
- **API Private Key** should correspond to NMI’s **Private Security Key** with the API Source.
- **API Public Key** should correspond to NMI’s **Public Security Key** with the Tokenization Source.

Once the new version is released today, we recommend updating the plugin and testing again.  
We are confident that this update will resolve the issues you are experiencing.

Thank you again for your collaboration and feedback.

Best regards,  
**Solution25 Team**

**Comment by danbolick** [comment]
@solution-25 Fantastic, and thank you for the prompt reply!

**Comment by solution-25** [comment]
Hi @danbolick,

We've just released **v1.0.5**, which includes several improvements that may help address your concerns:

- **Payment Method Visibility**: NMI payment methods can now be properly assigned to sales channels.
- **Updated Naming**: We've renamed "NMI Saved Cards" to "Saved Cards" for a clearer checkout experience.
- **Improved Security**: Sensitive fields like API keys are now masked in the configuration page.
- **Separated Sandbox and Live Keys**: There are now distinct fields for Sandbox and Production environments to prevent misconfiguration.

Regarding the credit card form — Once a payment method is selected on the Checkout page, the credit card form will appear after clicking **Pay**, allowing the customer to enter their details.

Please update to v1.0.5 and let us know if you continue to experience any issues.
